apiVersion: v1
kind: Pod
metadata:
  name: message-injection-test
  namespace: default
spec:
  containers:
  - name: message-injection-test
    image: busybox
    command: ['sh', '-c', 'for i in `seq 1 1000`; do if i%5 then echo "Error message: $1"; else then echo "Correct message: $1"; fi; done']
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 100m
        memory: 100Mi
   
    
   