apiVersion: v1
kind: Secret
metadata:
  name: keda-rabbitmq-secret
  namespace: default
data:
  RabbitMqHost: YW1xcHM6Ly9VU0VSOlBBU1NASE9TVC9WSE9TVA==

---

apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-rabbitmq-trigger
  namespace: default
spec:
  secretTargetRef:
    - parameter: host
      name: keda-rabbitmq-secret
      key: RabbitMqHost

---

apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: keda-rabbitmq-all-message-queue
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rabbitmq-all-message-queue
  pollingInterval: 5
  cooldownPeriod: 30
  maxReplicaCount: 30
  triggers:
  - type: rabbitmq
    name: keda-rabbitmq-trigger-all-message-queue
    metadata:
      protocol: amqp
      queueName: all-messages
      value: '5'
    authentication:
      secretTargetRef:
        - parameter: host
          key: RabbitMqHost

---

apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: keda-rabbitmq-error-message-queue
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rabbitmq-error-message-queue
  pollingInterval: 5
  cooldownPeriod: 30
  maxReplicaCount: 30
  triggers:
  - type: rabbitmq
    name: keda-rabbitmq-trigger-error-message-queue
    metadata:
      protocol: amqp
      queueName: error_message
      value: "5"
    authentication:
      secretTargetRef:
        - parameter: host
          name: keda-rabbitmq-secret

---

apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: keda-rabbitmq-good-message-queue
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rabbitmq-good-message-queue
  pollingInterval: 5
  cooldownPeriod: 30
  maxReplicaCount: 30
  triggers:
  - type: rabbitmq
    name: keda-rabbitmq-trigger-error-message-queue
    metadata:
      protocol: amqp
      queueName: good_message
      value: "5"
    authentication:
      secretTargetRef:
        - parameter: host
          name: keda-rabbitmq-secret
